### ISSUE TITLE
Please compare to this project to avoid duplicated effort

### ISSUE THREAD

**Issue by hansfbaier** [adafruit/usb_descriptor#11]
Hi, thanks for the great work!
I recently contributed a rather comprehensive implementation of the USB2 audio spec
to this project:
https://github.com/usb-tools/python-usb-protocol
This project does something very similar:
Generate binary USB descriptors from python.

**Comment by tannewt** [comment]
Good idea. We don't use this repo anymore too. Will archive. Just added a link to the repo you provided. Thanks!
