### ISSUE TITLE
"A current usage example" link in README is broken

### ISSUE THREAD

**Issue by mithro** [adafruit/usb_descriptor#5]
In the README there is a link to `https://github.com/adafruit/circuitpython/blob/master/ports/atmel-samd/tools/gen_usb_descriptor.py` which doesn't not seem to exist anymore.

> A current usage example that generates descriptors MicroChip's ASF4 can be found here in CircuitPython.

**Comment by tannewt** [comment]
Updated in https://github.com/adafruit/usb_descriptor/commit/ad2449cedbdac3d355b18de9d41f14e42c12dc26. Thanks!
